spring.application.name=wms-monitor-service
server.port=8081

# ================= MAIL DB (for email_config + mail_config) =================
maildb.url=jdbc:oracle:thin:@192.168.200.83:1521:SCPRD
maildb.username=wmwhse1
maildb.password=WMwhSqlWMwhSql1


# ================= DUBAI =================
wh1.name=WH1_DXB
wh1.url=jdbc:oracle:thin:@192.168.200.83:1521:SCPRD
wh1.username=wmwhse1
wh1.password=WMwhSqlWMwhSql1

wh3.name=WH3_DXB
wh3.url=jdbc:oracle:thin:@192.168.200.83:1521:SCPRD
wh3.username=wmwhse3
wh3.password=WMwhSqlWMwhSql3

wh4.name=WH4_DXB
wh4.url=jdbc:oracle:thin:@192.168.200.83:1521:SCPRD
wh4.username=wmwhse4
wh4.password=WMwhSqlWMwhSql4

wh5.name=WH5_DXB
wh5.url=jdbc:oracle:thin:@192.168.200.83:1521:SCPRD
wh5.username=wmwhse5
wh5.password=WMwhSqlWMwhSql5


# ================= KSA =================
wh2.name=WH2_KSA
wh2.url=jdbc:oracle:thin:@172.20.8.104:1521:SCPRD
wh2.username=wmwhse2
wh2.password=WMwhSqlWMwhSql2

wh6.name=WH6_KSA
wh6.url=jdbc:oracle:thin:@172.20.8.104:1521:SCPRD
wh6.username=wmwhse6
wh6.password=WMwhSqlWMwhSql6