spring.application.name=wms-monitor-service
server.port=8081

# ================= MAIL DB =================
maildb.url=${MAILDB_URL}
maildb.username=${MAILDB_USER}
maildb.password=${MAILDB_PASS}

# ================= DUBAI =================
wh1.name=WH1_DXB
wh1.url=${WH1_URL}
wh1.username=${WH1_USER}
wh1.password=${WH1_PASS}
 
wh3.name=WH3_DXB
wh3.url=${WH3_URL}
wh3.username=${WH3_USER}
wh3.password=${WH3_PASS}

wh4.name=WH4_DXB
wh4.url=${WH4_URL}
wh4.username=${WH4_USER}
wh4.password=${WH4_PASS}

wh5.name=WH5_DXB
wh5.url=${WH5_URL}
wh5.username=${WH5_USER}
wh5.password=${WH5_PASS}

# ================= KSA =================
wh2.name=WH2_KSA
wh2.url=${WH2_URL}
wh2.username=${WH2_USER}
wh2.password=${WH2_PASS}

wh6.name=WH6_KSA
wh6.url=${WH6_URL}
wh6.username=${WH6_USER}
wh6.password=${WH6_PASS}