package com.wms.monitor.service;

import com.wms.monitor.entity.MonitorLog;
import com.wms.monitor.entity.WarehouseConfig;
import com.wms.monitor.repository.MonitorRepository;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class MonitorService {

    @Autowired
    private WarehouseConfigService warehouseService;

    @Autowired
    private DynamicConnectionService connectionService;

    @Autowired
    private MonitorRepository repository;

    public MonitorResult generateExcelReport() throws Exception {

        Workbook workbook = new XSSFWorkbook();

        String dateTime = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm:ss"));

        String generatedBy = System.getProperty("user.name");
        String client = "REDTAG";

        // ================= STYLES =================
        CellStyle headerStyle = workbook.createCellStyle();
        Font headerFont = workbook.createFont();
        headerFont.setBold(true);
        headerFont.setColor(IndexedColors.WHITE.getIndex());
        headerStyle.setFont(headerFont);
        headerStyle.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
        headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        headerStyle.setAlignment(HorizontalAlignment.CENTER);

        // 🔥 Add borders (NEW)
        headerStyle.setBorderBottom(BorderStyle.THIN);
        headerStyle.setBorderTop(BorderStyle.THIN);
        headerStyle.setBorderLeft(BorderStyle.THIN);
        headerStyle.setBorderRight(BorderStyle.THIN);

        // Center style
        CellStyle centerStyle = workbook.createCellStyle();
        centerStyle.setAlignment(HorizontalAlignment.CENTER);

        // Red style
        CellStyle redStyle = workbook.createCellStyle();
        redStyle.setFillForegroundColor(IndexedColors.RED.getIndex());
        redStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        redStyle.setAlignment(HorizontalAlignment.CENTER);

        // Orange style
        CellStyle orangeStyle = workbook.createCellStyle();
        orangeStyle.setFillForegroundColor(IndexedColors.ORANGE.getIndex());
        orangeStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        orangeStyle.setAlignment(HorizontalAlignment.CENTER);

        // ================= SUMMARY =================
        Sheet summary = workbook.createSheet("SUMMARY");

        Row meta1 = summary.createRow(0);
        meta1.createCell(0).setCellValue("Generated On:");
        meta1.createCell(1).setCellValue(dateTime);

        Row meta2 = summary.createRow(1);
        meta2.createCell(0).setCellValue("Generated By:");
        meta2.createCell(1).setCellValue(generatedBy);

        Row meta3 = summary.createRow(2);
        meta3.createCell(0).setCellValue("Client:");
        meta3.createCell(1).setCellValue(client);

        // 🔥 HEADER WITH STYLE (FIX)
        Row header = summary.createRow(4);

        Cell sh1 = header.createCell(0);
        sh1.setCellValue("Warehouse");
        sh1.setCellStyle(headerStyle);

        Cell sh2 = header.createCell(1);
        sh2.setCellValue("Issues");
        sh2.setCellStyle(headerStyle);

        int summaryRow = 5;

        boolean hasMismatch = false;
        StringBuilder mismatchWh = new StringBuilder();

        // ================= LOOP =================
        for (WarehouseConfig config : warehouseService.getAllWarehouses()) {

            boolean warehouseMismatch = false;

            try (Connection conn = connectionService.getConnection(config)) {

                repository.runMonitorProcedure(conn);
                List<MonitorLog> logs = repository.getLogs(conn);

                Sheet sheet = workbook.createSheet(config.getName());

                // META
                Row info1 = sheet.createRow(0);
                info1.createCell(0).setCellValue("Generated On:");
                info1.createCell(1).setCellValue(dateTime);

                Row info2 = sheet.createRow(1);
                info2.createCell(0).setCellValue("Generated By:");
                info2.createCell(1).setCellValue(generatedBy);

                Row info3 = sheet.createRow(2);
                info3.createCell(0).setCellValue("Client:");
                info3.createCell(1).setCellValue(client);

                // HEADER
                Row h = sheet.createRow(4);
                String[] headers = {"Check Code", "Description", "Row Count", "Updated Rows"};

                for (int i = 0; i < headers.length; i++) {
                    Cell cell = h.createCell(i);
                    cell.setCellValue(headers[i]);
                    cell.setCellStyle(headerStyle);
                }

                int rowNum = 5;
                int issueCount = 0;

                if (logs != null) {
                    for (MonitorLog log : logs) {

                        Row row = sheet.createRow(rowNum++);

                        row.createCell(0).setCellValue(log.getCheckCode());
                        row.createCell(1).setCellValue(log.getCheckDesc());

                        Cell rowCountCell = row.createCell(2);
                        rowCountCell.setCellValue(log.getRowCount());

                        Cell updatedCell = row.createCell(3);
                        updatedCell.setCellValue(log.getUpdatedRows());
                        updatedCell.setCellStyle(centerStyle);

                        if (log.getRowCount() > 50) {
                            rowCountCell.setCellStyle(redStyle);
                            issueCount++;
                            hasMismatch = true;
                            warehouseMismatch = true;
                        } else if (log.getRowCount() > 0) {
                            rowCountCell.setCellStyle(orangeStyle);
                            issueCount++;
                            hasMismatch = true;
                            warehouseMismatch = true;
                        } else {
                            rowCountCell.setCellStyle(centerStyle);
                        }
                    }
                }

                sheet.createFreezePane(0, 5);

                for (int i = 0; i < 4; i++) {
                    sheet.autoSizeColumn(i);
                }

                // SUMMARY DATA
                Row sRow = summary.createRow(summaryRow++);
                sRow.createCell(0).setCellValue(config.getName());
                sRow.createCell(1).setCellValue(issueCount);

                if (warehouseMismatch) {
                    if (mismatchWh.length() > 0) mismatchWh.append(", ");
                    mismatchWh.append(config.getName());
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        summary.autoSizeColumn(0);
        summary.autoSizeColumn(1);

        File file = new File("WMS_Report.xlsx");

        try (FileOutputStream out = new FileOutputStream(file)) {
            workbook.write(out);
        }

        workbook.close();

        return new MonitorResult(file, hasMismatch, mismatchWh.toString(), dateTime);
    }
}